apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: amrsupgrade-claim0
  name: amrsupgrade-claim0
  annotations:
    volume.beta.kubernetes.io/storage-class: "cstor-disk-pool-default"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
status: {}
