apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: amrsupgrade
  name: amrsupgrade
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: amrsupgrade
    spec:
      containers:
      - env:
        - name: CATALINA_OPTS
          value: -Xmx12g -Xms12g -XX:MaxPermSize=1024m
        - name: DB_NAME
          value: amrs
        - name: OPENMRS_DB_PASS
          value: debezium
        - name: OPENMRS_DB_USER
          value: debezium
        - name: OPENMRS_MYSQL_HOST
          value: 10.50.80.115
        - name: OPENMRS_MYSQL_PORT
          value: "3306"
        - name: OPENMRS_NAME
          value: amrs-backup
        - name: TZ
          value: Africa/Nairobi
        image: enyachoke/openmrs-2.1.1-spa
        imagePullPolicy: Always
        name: amrsupgrade
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 15Gi
          limits:
            memory: 20Gi
        volumeMounts:
        - mountPath: /root/.OpenMRS
          name: amrsupgrade-claim0
      restartPolicy: Always
      
      volumes:
      - name: amrsupgrade-claim0
        persistentVolumeClaim:
          claimName: amrsupgrade-claim0
status: {}
